export type Category = '장학금'|'학자금'|'알바'|'자취'|'월세'|'이사'|'학교'|'휴학'|'졸업'|'취업'|'세금'|'군대'|'해외'|'신분증'|'증명서'|'병원'|'사기'|'유학생';
export type VerificationStatus = 'verified'|'institution-specific'|'pending';
export type ApplicationMethod = '온라인'|'방문'|'온라인·방문'|'기관별 확인 필요';
export type ConditionOption = { value:string; label:string };
export type ConditionQuestion = { id:string; question:string; helpText?:string; options:ConditionOption[]; required:boolean };
export type RequiredDocument = { id:string; name:string; description:string; issueUrl?:string; sourceUrl?:string; condition?:{questionId:string;values:string[]} };
export type ProcedureStep = { id:string; order:number; title:string; description:string; method?:string; caution?:string; sourceUrl?:string; condition?:{questionId:string;values:string[]} };
export type Procedure = {
  id:string;
  category:Category;
  title:string;
  searchKeywords:string[];
  aliases:string[];
  summary:string;
  targetUsers:string[];
  eligibility:string[];
  conditionQuestions:ConditionQuestion[];
  requiredDocuments:RequiredDocument[];
  steps:ProcedureStep[];
  applicationMethod:ApplicationMethod;
  responsibleAgency:string;
  officialApplicationUrl?:string;
  officialSourceUrls:string[];
  fee:string;
  processingTime:string;
  exceptions:string[];
  lastVerifiedAt:string;
  notice:string;
  verificationStatus:VerificationStatus;
};
